version: "1"
services:
  # Database
  db:
    container_name: db_container
    image: mysql:8.0.35
    volumes:
      - db_data:/var/lib/mysql
      - ./0_db_dump.sql:/docker-entrypoint-initdb.d/0_db_dump.sql
      - ./1_user.sql:/docker-entrypoint-initdb.d/1_user.sql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    #entrypoint:
      #sh -c ""
    networks:
      - wpNetwork

  # phpmyadmin
  phpmyadmin:
    container_name: phpMyAdmin_container
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    ports:
      - "80:80"
    env_file: .env
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
      - wpNetwork

  # WordPress
  wordpress:
    container_name: wordpress_container
    depends_on:
      - db
    image: wordpress:6.1.1
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./:/var/www/html/yourwordpresswebsite.com
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
    networks:
      - wpNetwork

networks:
  wpNetwork:

volumes:
  db_data: